# Generated by Django 5.2.4 on 2025-07-12 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Parte cadastro", "Parte cadastro"),
                            ("Parte financeira", "Parte financeira"),
                            ("Parte completada", "Parte completada"),
                        ],
                        default="Parte cadastro",
                        max_length=50,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor total",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Data")),
                (
                    "installments",
                    models.BooleanField(
                        default=False, verbose_name=" Essa conta é parcelada"
                    ),
                ),
                (
                    "due_date_day",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Dia vencimento",
                    ),
                ),
                (
                    "installment_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número de parcelas"
                    ),
                ),
                (
                    "store",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Loja"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.profile",
                        verbose_name="Proprietário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Pago", "Pago"), ("Nao Pago", "Nao Pago")],
                        default="Nao Pago",
                        max_length=50,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "installment_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor parcelas",
                    ),
                ),
                (
                    "maturity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vencimento da Parcela"
                    ),
                ),
                (
                    "accounts",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                        verbose_name="conta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcela",
                "verbose_name_plural": "Parcelas",
            },
        ),
    ]
