# Generated by Django 3.2.12 on 2023-10-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('Parte cadastro', 'Parte cadastro'), ('Parte financeira', 'Parte financeira')], default='Parte cadastro', max_length=30, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='account',
            name='installment_number',
            field=models.IntegerField(blank=True, max_length=5, null=True, verbose_name='Nuúmero de parcelas'),
        ),
        migrations.AlterField(
            model_name='account',
            name='installments',
            field=models.BooleanField(default=False, verbose_name=' Essa conta é parcelada?'),
        ),
        migrations.AlterField(
            model_name='account',
            name='store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='account',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor total'),
        ),
    ]
