# Generated by Django 5.2.4 on 2025-07-12 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_contamensais"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contamensais",
            options={
                "verbose_name": "Conta mensal",
                "verbose_name_plural": "Conta Mensais",
            },
        ),
        migrations.AlterModelOptions(
            name="tipoconta",
            options={
                "verbose_name": "Tipo Conta",
                "verbose_name_plural": "Tipos Contas",
            },
        ),
        migrations.AddField(
            model_name="contamensais",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.profile",
                verbose_name="Proprietário",
            ),
        ),
    ]
