# Generated by Django 5.2.4 on 2025-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_alter_contamensais_options_alter_tipoconta_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contamensais",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Pago", "Pago"), ("Nao Pago", "Nao Pago")],
                default="Nao Pago",
                max_length=50,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
