# Generated by Django 3.2.12 on 2023-10-03 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20231003_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor parcelas')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor total pago')),
                ('he_must', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Falta Pagar')),
                ('month_year', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mes e ano de termino')),
                ('accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account', verbose_name='conta')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
            },
        ),
    ]
