# Generated by Django 3.2.12 on 2023-10-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_installment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='he_must',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='month_year',
        ),
        migrations.AddField(
            model_name='installment',
            name='maturity',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento da Parcela'),
        ),
        migrations.AddField(
            model_name='installment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pago', 'Pago'), ('Em Haver', 'Em Haver')], default='Em Haver', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
