# Generated by Django 3.2.12 on 2023-10-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20231006_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='due_date_day',
            field=models.TextField(blank=True, null=True, verbose_name='Dia de vencimento'),
        ),
    ]
