# Generated by Django 3.2.12 on 2023-10-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_due_date_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='due_date_day',
        ),
    ]
