# Generated by Django 3.2.12 on 2023-10-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_due_date_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='accounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='conta'),
        ),
    ]
