# Generated by Django 3.2.12 on 2023-10-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_installment_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pago', 'Pago'), ('Nao Pago', 'Nao Pago')], default='Nao Pago', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
