# Generated by Django 3.2.12 on 2025-02-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('accounts', '0012_alter_installment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profile', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='account',
            name='installment_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de parcelas'),
        ),
    ]
