# Generated by Django 5.2.4 on 2025-07-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Tipo Entrada",
                "verbose_name_plural": "Tipos Entradas",
            },
        ),
    ]
